trigger:
- master

variables:
- group: CustodianCoreCI

jobs:

- job: 'CustodianCask'
  displayName: 'Tool Tests - Cask'
  pool:
    vmImage: 'Ubuntu-18.04'

  steps:
  - task: GoTool@0
    inputs:
      version: '1.12.6'

  - script: make test
    workingDirectory: tools/cask/
    displayName: 'Build for all platforms'


- job: 'CustodianOmniSSM'
  displayName: 'Tool Tests - OmniSSM'
  pool:
    vmImage: 'Ubuntu-18.04'

  steps:
  - task: GoTool@0
    inputs:
      version: '1.12.6'
  - script: make test
    workingDirectory: tools/omnissm/
    displayName: 'Test'
